In [1]:
#SVD
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components, :]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
